# 作业-Numpy

运用Numpy1维、2维数组相关的创建、切片、运算等方法解决以下问题：

## 1. 一维数组（0.5分\*4 = 2分）
- 创建一个1维数组，命名为data01，包含100，99，...，1，间隔为1
- 对其进行从小到大排序
- 将数组data01变形成4行25列的2维数组
- 计算总和

In [3]:
import numpy as np
data01 = np.arange(100, 0, -1)
data01

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [4]:
np.sort(data01)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
data01.reshape(4, 25)

array([[100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
         87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76],
       [ 75,  74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,
         62,  61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,
         37,  36,  35,  34,  33,  32,  31,  30,  29,  28,  27,  26],
       [ 25,  24,  23,  22,  21,  20,  19,  18,  17,  16,  15,  14,  13,
         12,  11,  10,   9,   8,   7,   6,   5,   4,   3,   2,   1]])

In [6]:
data01.sum()

5050

## 2.二维数组（0.5分\*6=3分）
- 创建一个大小为3行4列的2维随机数组，数组中的元素维随机数，命名为data02
- 选取数组data02后3列，也就是第2列到第4列元素
- 求数组data02的元素中的最大值、最小值和总和。
- 求数组data02的元素中的每一列求最大值、最小值和总和。
- 将data02变形成1维数组。
- 将data02变成4行3列的2维数组



In [22]:
data02 = np.random.rand(3,4)  #也可以使用np.random.randint生成随机证书 
data02

array([[0.80720115, 0.31225948, 0.84573254, 0.69912808],
       [0.29635292, 0.17884995, 0.3244918 , 0.76705679],
       [0.39717038, 0.13558286, 0.98839005, 0.67591629]])

In [23]:
data02[:, -3:]

array([[0.31225948, 0.84573254, 0.69912808],
       [0.17884995, 0.3244918 , 0.76705679],
       [0.13558286, 0.98839005, 0.67591629]])

In [24]:
data02.max(), data02.min(), data02.sum()

(0.9883900508063549, 0.135582859038331, 6.428132287096357)

In [28]:
data02.max(axis=0), data02.max(axis=1), data02.sum(axis=0)

(array([0.80720115, 0.31225948, 0.98839005, 0.76705679]),
 array([0.84573254, 0.76705679, 0.98839005]),
 array([1.50072445, 0.62669229, 2.15861439, 2.14210116]))

In [32]:
data02.ravel()  #或者 data02.flatten()

array([0.80720115, 0.31225948, 0.84573254, 0.69912808, 0.29635292,
       0.17884995, 0.3244918 , 0.76705679, 0.39717038, 0.13558286,
       0.98839005, 0.67591629])

In [34]:
data02.reshape(4,3)

array([[0.80720115, 0.31225948, 0.84573254],
       [0.69912808, 0.29635292, 0.17884995],
       [0.3244918 , 0.76705679, 0.39717038],
       [0.13558286, 0.98839005, 0.67591629]])

## 3.最小最大标准化(1分)

最小最大标准化（Min-Max Normalization）是一种常用的数据标准化方法，用于将数据缩放到指定的范围内。
该方法通过对数据进行线性变换，使其值域被缩放到指定的范围内，通常是 [0,1] 或 [-1,1]。

该方法的公式如下：

$$
X_{norm} = (X - X_{min}) / (X_{max} - X_{min})
$$

通过最小最大标准化，可以使得不同量纲的数据在同一标度下进行比较，且可以使得数据具有可比性。
在机器学习、数据挖掘等领域中，常常需要对数据进行标准化，以提高算法的性能和效果。

应用上述方法，将序列[16, 46, 33, 90, 64, 34, 91, 33, 24, 32, 30, 91, 85, 58, 77, 35,  1,34, 51, 36]进行最小最大标准化操作，放缩到[0,1]。

In [36]:
X = np.array([16, 46, 33, 90, 64, 34, 91, 33, 24, 32, 30, 91, 85, 58, 77, 35, 1,34, 51, 36])
X_norm = (X-X.min())/(X.max() - X.min())
X_norm

array([0.16666667, 0.5       , 0.35555556, 0.98888889, 0.7       ,
       0.36666667, 1.        , 0.35555556, 0.25555556, 0.34444444,
       0.32222222, 1.        , 0.93333333, 0.63333333, 0.84444444,
       0.37777778, 0.        , 0.36666667, 0.55555556, 0.38888889])

## 4. 数据集划分（2分\*2=4分）

在机器学习中，样本内和样本外是指数据集中的一部分样本，其中来说，样本内是指用于训练模型、调整模型参数、验证模型性能的数据；样本外是指未在训练过程中使用的数据，通常用于测试模型的性能和泛化能力。

![fix_split](image/fix_split.png)

一般将80%的原始数据集的子样本集作为样本内(In-sample, IS)，剩余20%作为样本外(Out-of-sample, OOS)。
样本总数为500个，一种简单的切割方法是直接指定前400个样本为IS，后面为OOS。

In [37]:
X = np.array([0.36707772, 0.30442107, 0.09602864, 0.72140911, 0.30727176,
       0.30332833, 0.82704939, 0.0547752 , 0.91921485, 0.54352647,
       0.45263199, 0.1654269 , 0.42571673, 0.38253443, 0.11461271,
       0.56558215, 0.78277293, 0.82637154, 0.48652071, 0.49557472])

如果给定一个X序列，那么其样本内和样本外分别是：

In [41]:
X_IS = X[:int(len(X)*0.8)]
X_OOS = X[int(len(X)*0.8):]

简单随机划分（Simple Random Sampling）：将原始数据集随机划分为训练集和测试集两部分，通常将数据集的 70% 到 80% 作为训练集，剩余部分作为测试集。

![random_split](image/random_split.png)

当我们并不了解原始数据集是不是被刻意排列了，最好的办法是使用随机抽样，即随机抽80%为IS，剩余的20%为OOS。

In [47]:
arr = np.arange(len(X))
np.random.shuffle(arr)
arr

array([19,  8,  1,  5, 11, 15, 18,  7,  9, 12,  3, 10, 13, 16,  4,  6,  2,
        0, 14, 17])

In [50]:
X_random_IS = X[arr[:int(len(arr)*0.8)]]
X_random_OOS = X[arr[int(len(arr)*0.8):]]