# 作业-Numpy

## 1. 一维数组（0.25分\*4 = 1分）
- 创建一个1维数组，命名为data01，包含100，99，...，1，间隔为1
- 对其进行从小到大排序
- 将数组data01变形成4行25列的2维数组
- 计算总和

In [3]:
import numpy as np
data01 = np.arange(100, 0, -1)
data01

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [4]:
np.sort(data01)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
data01.reshape(4, 25)

array([[100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
         87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76],
       [ 75,  74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,
         62,  61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,
         37,  36,  35,  34,  33,  32,  31,  30,  29,  28,  27,  26],
       [ 25,  24,  23,  22,  21,  20,  19,  18,  17,  16,  15,  14,  13,
         12,  11,  10,   9,   8,   7,   6,   5,   4,   3,   2,   1]])

In [6]:
data01.sum()

5050

## 2. 评估销售信息（0.5分*2=1分）
假设有一个销售数据集：[100, 150, 200, 120, 180, 90, 160, 220, 130, 190]，
1. 计算销售数量的总和
2. 计算销售数量的平均值
3. 计算销售数量的标准差

In [ ]:
import numpy as np

# 假设有一个销售数据集
sales_data = np.array([100, 150, 200, 120, 180, 90, 160, 220, 130, 190])

# 计算销售数量的总和
total_sales = np.sum(sales_data)
print("总销售数量：", total_sales)

# 计算销售数量的平均值
average_sales = np.mean(sales_data)
print("平均销售数量：", average_sales)


## 3.最小最大标准化(1分)

最小最大标准化（Min-Max Normalization）是一种常用的数据标准化方法，用于将数据缩放到指定的范围内。
该方法通过对数据进行线性变换，使其值域被缩放到指定的范围内，通常是 [0,1] 或 [-1,1]。

该方法的公式如下：

$$
X_{norm} = (X - X_{min}) / (X_{max} - X_{min})
$$

通过最小最大标准化，可以使得不同量纲的数据在同一标度下进行比较，且可以使得数据具有可比性。
在机器学习、数据挖掘等领域中，常常需要对数据进行标准化，以提高算法的性能和效果。

应用上述方法，将序列[16, 46, 33, 90, 64, 34, 91, 33, 24, 32, 30, 91, 85, 58, 77, 35,  1,34, 51, 36]进行最小最大标准化操作，放缩到[0,1]。

### 答案：

In [ ]:
X = np.array([16, 46, 33, 90, 64, 34, 91, 33, 24, 32, 30, 91, 85, 58, 77, 35, 1,34, 51, 36])
X_norm = (X-X.min())/(X.max() - X.min())
X_norm

## 4. 数据集划分——固定划分（1分）

在机器学习中，样本内和样本外是指数据集中的一部分样本，其中来说，样本内是指用于训练模型、调整模型参数、验证模型性能的数据；样本外是指未在训练过程中使用的数据，通常用于测试模型的性能和泛化能力。

![fix_split](image/fix_split.png)

一般将80%的原始数据集的子样本集作为样本内(In-sample, IS)，剩余20%作为样本外(Out-of-sample, OOS)。
样本总数为500个，一种简单的切割方法是直接指定前400个样本为IS，后面为OOS。

In [48]:
X = np.array([0.36707772, 0.30442107, 0.09602864, 0.72140911, 0.30727176,
       0.30332833, 0.82704939, 0.0547752 , 0.91921485, 0.54352647,
       0.45263199, 0.1654269 , 0.42571673, 0.38253443, 0.11461271,
       0.56558215, 0.78277293, 0.82637154, 0.48652071, 0.49557472])

如果给定一个X序列，那么其样本内和样本外分别是：

In [ ]:
X_IS = 
X_OOS = 

### 答案：

In [ ]:
X_IS = X[:int(len(X)*0.8)]
X_OOS = X[int(len(X)*0.8):]

## 5. 数据集划分——简单随机划分（1分）

简单随机划分（Simple Random Sampling）：将原始数据集随机划分为训练集和测试集两部分，通常将数据集的 70% 到 80% 作为训练集，剩余部分作为测试集。

![random_split](image/random_split.png)

当我们并不了解原始数据集是不是被刻意排列了，最好的办法是使用随机抽样，即随机抽80%为IS，剩余的20%为OOS。

In [ ]:
X_random_IS = 
X_random_OOS = 

### 答案


In [ ]:
arr = np.arange(len(X))
np.random.shuffle(arr)
X_random_IS = X[arr[:int(len(arr)*0.8)]]
X_random_OOS = X[arr[int(len(arr)*0.8):]]